image: registry.gitlab.com/paddy-hack/nikola

test:
  script:
    - pip install babel
    - nikola build
  except:
    - master

pages:
  script:
    - pip install babel
    - nikola build
  artifacts:
    paths:
      - public
  only:
    - master