image: registry.gitlab.com/paddy-hack/nikola
build:
  stage: build
  script:
    - pip3 install babel
    - nikola build -a
pages:
  stage: deploy
  script:
    - nikola deploy gitlab
  only:
    - master
  artifacts:
    paths:
      - public
